#!/bin/bash

# Set your GitHub username and password here
username= Swiftminale
password=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

repository_url=$(git remote get-url origin)

git add .
git commit -m "first commit"
git push https://$username:$password@$repository_url

# Clearing the stored credentials
unset username
unset password

